<?xml version="1.0" encoding="utf-8"?><Database Name="Meeting Organizer" Class="MeetingOrganizer" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Events">
    <Type Name="Events">
      <Column Name="id" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="creatorId" Member="CreatorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="invitee" Member="Invitee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Member="Title" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="subject" Member="Subject" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="endTime" Member="EndTime" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="startTime" Member="StartTime" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Events_EventsTimeSlotRelations" Member="EventsTimeSlotRelations" ThisKey="Id" OtherKey="EventId" Type="EventsTimeSlotRelations" />
      <Association Name="Users_Events" Member="Users" ThisKey="CreatorId" OtherKey="Id" Type="Users" IsForeignKey="true" />
      <Association Name="Users_Events1" Member="InviteeUsers" ThisKey="Invitee" OtherKey="Id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="EventsTimeSlotRelations">
    <Type Name="EventsTimeSlotRelations">
      <Column Name="eventId" Member="EventId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="timeSlotId" Member="TimeSlotId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Events_EventsTimeSlotRelations" Member="Events" ThisKey="EventId" OtherKey="Id" Type="Events" IsForeignKey="true" />
      <Association Name="TimeSlots_EventsTimeSlotRelations" Member="TimeSlots" ThisKey="TimeSlotId" OtherKey="Id" Type="TimeSlots" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="TimeSlots">
    <Type Name="TimeSlots">
      <Column Name="id" Member="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="start" Member="Start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end" Member="End" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TimeSlots_EventsTimeSlotRelations" Member="EventsTimeSlotRelations" ThisKey="Id" OtherKey="TimeSlotId" Type="EventsTimeSlotRelations" />
    </Type>
  </Table>
  <Table Name="Users">
    <Type Name="Users">
      <Column Name="id" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Member="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="login" Member="Login" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Member="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Users_Events" Member="Events" ThisKey="Id" OtherKey="CreatorId" Type="Events" />
      <Association Name="Users_Events1" Member="InviteeID" ThisKey="Id" OtherKey="Invitee" Type="Events" />
    </Type>
  </Table>
</Database>